import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { clsx } from 'cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body className={clsx(poppins.variable, 'antialiased')}>{children}</body>
    </html>
  );
}
